unstable_features = true
edition = "2021"
indent_style = "Visual"
reorder_imports = true
tab_spaces = 4
imports_granularity = "Crate"
brace_style = "PreferSameLine"
use_field_init_shorthand = true
normalize_comments = true
reorder_impl_items = true
space_after_colon = true
struct_field_align_threshold = 25
struct_lit_single_line = true
use_try_shorthand = true
fn_single_line = true
format_code_in_doc_comments = true
fn_call_width = 120